### ISSUE TITLE
No issue, but a question

### ISSUE THREAD

**Issue by hagenbauer** [t-animal/covid-karte#10]
Great work. I would like to "rebuild" a local map. Is there an easy way to rebuild something like this https://civitec.maps.arcgis.com/apps/dashboards/0453cba02245458e869241f4070a4393 by changing urls to data? Or would this require programming skills?

**Comment by t-animal** [comment]
I'm afraid it's not just as easy as changing some data urls. You'd definitely need to develop some typescript and some additional data, like the map as geojson/topojson
