### ISSUE TITLE
Eisenach ist in den RKI Daten einfach Teil von LK Wartburgkreis.

### ISSUE THREAD

**Issue by quantenzitrone** [t-animal/covid-karte#11]
Auf der Karte ist ein kleiner weißer Fleck, bei dem steht:

> Eisenach, Thüringen
> Noch nicht den RKI Daten zugeordnet.
> [...]

Nach Abgleich der beiden Karten auf [covid-karte.de](https://covid-karte.de/#387) und [offizieller RKI-Karte](https://experience.arcgis.com/experience/478220a4c454480e823b17327b2bf1d4) bin ich mir recht sicher, dass Eisenach in den Daten Teil von  LK Wartburgkreis ist, da LK Wartburgkreis auf beiden Karten genau die gleichen Zahlen hat.

Da Eisenach ganz sicher mehr als 0 Covid-19 Fälle hatte, kann man dies schlussfolgern. 

Es sei denn, die Daten auf der offiziellen Karte vom RKI sind falsch.

**Comment by fnogatz** [comment]
Das Excelfile des RKI führt seit geraumer Zeit dazu diesen Hinweis:

> * Nach einer Kreisgebietsreform werden Fälle und Inzidenzen für SK Eisenach seit 14.07.2021 zusammen unter LK Wartburgkreis aufgeführt

**Comment by t-animal** [comment]
Ich hatte lange keine Zeit und Motivation, das Problem zu fixen und hatte einen halbgaren fix schon seit Dezember rumfliegen (Die Animation hat das ganze leider etwas unschön gemacht). Den hab ich jetzt nochmal aufgehübscht und deployed.

**Comment by quantenzitrone** [comment]
ehre 👌️
