### ISSUE TITLE
Add positive rates for all graphs and tables

### ISSUE THREAD

**Issue by svdHero** [t-animal/covid-karte#3]
Hi there,

great app. Thank you for all your work.

Could you add a user setting where one can switch from absolute numbers and Sieben-Tage-Inzidenz to relative positive rates, i.e. Covid cases per number of tests?

That would be helpful.

Have a great day.

**Comment by t-animal** [comment]
Unless this is in the RKI api, I'm afraid, the answer is no.

**Comment by svdHero** [comment]
But the RKI API provides the number of tests, doesn't it?
So you just have to calculate the relative number by means of this Dreisatz-formula:
```
absoluteNumberOfNewInfections / numberOfTests * 100
```
in order to get the positive rate in percent.

Also for the Sieben-Tage-Inzidenz you could do
```
sevenDayIncidence / numberOfTestsInTheLastSevenDays * 100
```
That's basic high school math based on the official RKI numbers.

Would be great if you could provide that feature.

**Comment by t-animal** [comment]
Thanks for that very helpful lecture on maths, now I finally know what this "per-centum" means.

Anyways, as far as I know the RKI api does not provide the information you seek and I also can't find it on corona.rki.de so I can't cross-validate the results or even reverse it. If you find it somewhere in there, let me know and I may reconsider re-opening the issue. But please provide the direct link instead of making me search for it again.

![image](https://user-images.githubusercontent.com/1775745/111901069-129bce80-8a36-11eb-8c04-fed98cb4121b.png)

**Comment by svdHero** [comment]
Sorry, I did not want to lecture you, I merely wanted to explain that I was not implying any complicated or misleading formulas to tweak the numbers.

Also, I only assumed that the API provides the total number of tests, hence my "doesn't it".

Again, I apologize if my earlier posting came across too condescending. That was not my intention.

**Comment by svdHero** [comment]
Just for completeness sake: I've found this chart:
https://ourworldindata.org/grapher/positive-rate-daily-smoothed?tab=chart&time=earliest..2021-03-14&country=~DEU
whose data source is the RKI, however not as part of their web api. For more details see:
https://ourworldindata.org/coronavirus-testing#germany

Just in case anybody happens to come across this issue while searching for a chart of the positive rate in Germany.

@t-animal I hope this is okay. Thanks again for your work.

**Comment by t-animal** [comment]
Thanks for looking this up! Unfortunately this wouldn't help :( The ourworldindata data is aggregated already. And the RKI spreadsheet is 1) only updated weekly by the RKI and 2)  there is no link to the individual counties. Even if there were - creating the map between county-id and the corresponding data would be very tedious. I had to do it once before for the county-id to objectId and wouldn't wanna do it again.

Unfortunately it looks like the public health sector relies a lot on manual labor and spreadsheets and not on APIs (no surprise there, though).

**Comment by svdHero** [comment]
Ok. Thanks for considering and looking into it again.
