### ISSUE TITLE
7 day incidence display broken on mobile 

### ISSUE THREAD

**Issue by rupran** [t-animal/covid-karte#6]
On my phone, the 7 day incidence display only shows as an empty box, see the screen shot below.

![Screenshot_20210607-174547__01](https://user-images.githubusercontent.com/6428272/121050012-87221600-c7b8-11eb-8631-ed12c143c52e.jpg)

Browser: Google Chrome 90.0.4430.210
OS: Android 9

**Comment by t-animal** [comment]
Can you reproduce this in private browsing mode?

**Comment by rupran** [comment]
In private browsing mode the contents show up fine. 

However, clearing all site data does **not** fix it in the regular mode.

**Comment by t-animal** [comment]
Does this still happen on your phone?

**Comment by rupran** [comment]
No, the problem is fixed now (though I'm not sure why).

**Comment by t-animal** [comment]
Pretty sure this was a caching problem. I never bothered with setting this up properly, I'm afraid, so a couple of days after deployment things might be weird.
