### ISSUE TITLE
[Feature] RiskLayer (Feingranular) Option

### ISSUE THREAD

**Issue by parrot7483** [t-animal/covid-karte#8]
Mit momentan fallender Inzidenz wäre es cool wenn man einzelne Landkreise besser unterscheiden könnte. Eine Farbe (vlt. dunkel Grün?) für >0.01 und <5 wäre eine tolle Erweiterung.

**Comment by t-animal** [comment]
Ja... das Problem ist, dass RiskLayer das nicht umgestellt hat und ich wuerde die Karten gerne vergleichbar halten. Wenn du weisst, wie das geht kannst du aber schonmal in LocalStorage das labelScheme: "RiskLayerExtended" einstellen.

**Comment by t-animal** [comment]
Implemented in 7b741a2e54ba90ccdc9384b8a3d290d6f008c5c8 since risklayer introduced the new color after I asked. Neat!
